import Body from "@/components/Background";
import Footer from "@/components/Footer";
import GlobalStyles from "@/components/GlobalStyles";
import Header from "@/components/Header";
import localFont from "next/font/local";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import StyledComponentsRegistry from "@/lib/registry";

export const metadata = {
  title: "Trinh The Son",
  description: "Generated by create next app",
};

const wotfard = localFont({
  src: [
    {
      path: "../../public/fonts/wotfard-regular-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/wotfard-medium-webfont.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/wotfard-semibold-webfont.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/wotfard-bold-webfont.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/wotfard-regularitalic-webfont.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  display: "fallback",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={wotfard.className}
    >
      <head>
        <link rel="shortcut icon" href="/images/emoji.svg" type="image/x-icon" />
      </head>
      <StyledComponentsRegistry>
        <Body>
          <MaxWidthWrapper>
            <Header />
            {children}
            <Footer />
          </MaxWidthWrapper>
          <GlobalStyles />
        </Body>
      </StyledComponentsRegistry>
    </html>
  );
}
